services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    command: npm start
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
    command: node index.js
  mongo_db:
    container_name: mongo_container
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
    restart: always