services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "6001:6001"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo_db

  mongo_db:
    container_name: mongo_container
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: always

volumes:
  mongo_data:
